import test from 'node:test';
import assert from 'node:assert/strict';
import { Game, ROLES } from '../game.mjs';
const drawing=[{color:'#202031',size:5,points:[[.1,.1],[.5,.8],[.9,.2]]}];
function setup(n){let now=1000000;const game=new Game({now:()=>now});const host=game.create();const seats=Array.from({length:n},(_,i)=>game.join(host.room,`Player ${i+1}`));const room=game.room(host.room);const act=(seat,type,extra={})=>game.action(host.room,seat.token,{type,...extra});act(host,'start');const seatFor=id=>seats.find(s=>s.playerId===id);return {game,host,seats,room,act,seatFor,setNow:n=>now=n};}
function fillWriting(g){const {room:r,seatFor,act}=g;const t=r.t;act(seatFor(t.subject),'answer',{text:`True answer ${r.round}-${r.turnIndex}`,lie:'My personal lie'});for(const p of r.players)if(r.players.length>2&&p.id!==t.subject)act(seatFor(p.id),'answer',{text:`Lie from ${p.name}`});assert.equal(r.phase,'vote');}
function voteTruth(g){const truth=g.room.t.options.find(o=>o.truth).id;for(const p of g.game.eligible(g.room))g.act(g.seatFor(p.id),'vote',{choices:[truth]});assert.equal(g.room.phase,'reveal');}
for(const n of [2,3,4,8])test(`Complete ${n}-player match: generated questions, player questions, drawing, scores, replay`,()=>{const g=setup(n),{room:r,act,host,seatFor,game}=g;assert.equal(new Set(r.players.map(p=>p.role.id)).size,n);if(n===2)assert.ok(r.players.every(p=>!['forger','reader'].includes(p.role.id)));let normal=0,finales=0;
while(r.phase!=='finished'){if(r.phase==='write'){fillWriting(g);voteTruth(g);normal++;act(host,'next');}else if(r.phase==='questions'){for(const p of r.players){const target=r.assignments[p.id];act(seatFor(p.id),'question',{text:`What snack does ${r.players.find(p=>p.id===target).name} love?`});}assert.equal(Object.keys(r.questions).length,n);assert.equal(r.round,2);}else if(r.phase==='truth'){const truth='A movie theater';act(seatFor(r.t.subject),'truth',{text:truth});assert.equal(r.phase,'draw');const hostView=game.snapshot(r,host.token);assert.equal(hostView.turn.truth,undefined);assert.equal(hostView.turn.artist,undefined);for(const p of r.players){const view=game.snapshot(r,p.token);assert.equal(!!view.me.truth,p.id===r.t.subject||p.id===r.t.artist);assert.equal(view.turn.artist,undefined);}
for(const p of game.artists(r))act(seatFor(p.id),'drawing',{strokes:drawing});assert.equal(r.phase,'vote');for(const s of [host,...g.seats]){const view=game.snapshot(r,s.token);assert.ok(view.turn.options.every(o=>!('truth'in o)&&!('owners'in o)));}voteTruth(g);finales++;act(host,'next');}else assert.fail(`Unexpected ${r.phase}`);}
assert.equal(normal,n*2);assert.equal(finales,1);assert.ok(r.players.every(p=>p.score>=1000*(n-1)));assert.ok(game.snapshot(r,host.token).players.every(p=>p.role));act(host,'restart');assert.equal(r.phase,'lobby');assert.ok(r.players.every(p=>p.score===0));act(host,'start');assert.equal(r.phase,'write');});

test('Scoring: truth, a lie, and no vote are separate outcomes',()=>{const g=setup(4);fillWriting(g);const voters=g.game.eligible(g.room);const a=voters[0],b=voters[1],c=voters[2];const truth=g.room.t.options.find(o=>o.truth);const lie=g.room.t.options.find(o=>o.owners.includes(a.id));g.act(g.seatFor(a.id),'vote',{choices:[truth.id]});g.act(g.seatFor(b.id),'vote',{choices:[lie.id]});g.act(g.host,'advance');assert.equal(a.score,750);assert.equal(b.score,0);assert.equal(c.score,0);});

test('Private snapshots hide answers until voting and ownership until reveal',()=>{const g=setup(4);const t=g.room.t;g.act(g.seatFor(t.subject),'answer',{text:'super-secret-true-place'});for(const p of g.room.players){const s=g.game.snapshot(g.room,p.token);assert.equal(s.turn.truth,undefined);if(p.id!==t.subject)assert.ok(!JSON.stringify(s).includes('super-secret-true-place'));}assert.ok(!JSON.stringify(g.game.snapshot(g.room,g.host.token)).includes('super-secret-true-place'));for(const p of g.room.players.filter(p=>p.id!==t.subject))g.act(g.seatFor(p.id),'answer',{text:p.name});for(const seat of [g.host,...g.seats]){const s=g.game.snapshot(g.room,seat.token);assert.ok(s.turn.options.every(o=>!('owners'in o)&&!('truth'in o)));assert.ok(!JSON.stringify(s).includes('token'));}});

test('Host authorization, late joining, self-voting, duplicate voting, stale turn protection',()=>{const g=setup(4);assert.throws(()=>g.act(g.seats[0],'advance'),/Only the TV/);assert.throws(()=>g.game.join(g.host.room,'Late'),/started/);assert.throws(()=>g.game.snapshot(g.room,'bad token'),/verified/);fillWriting(g);const p=g.game.eligible(g.room)[0],seat=g.seatFor(p.id),own=g.room.t.options.find(o=>o.owners.includes(p.id)),truth=g.room.t.options.find(o=>o.truth);assert.throws(()=>g.act(seat,'vote',{choices:[own.id]}),/cannot vote/);assert.throws(()=>g.act(seat,'vote',{choices:[truth.id],turnId:'old'}),/ended/);g.act(seat,'vote',{choices:[truth.id]});assert.throws(()=>g.act(seat,'vote',{choices:[truth.id]}),/already locked/);});

test('All eight role powers have their stated effects and cannot be reused',()=>{
for(const role of ROLES){const g=setup(4),{room:r,act,seatFor,game}=g;const p=r.players.find(p=>p.id!==r.t.subject);p.role=role;const other=r.players.find(q=>q.id!==r.t.subject&&q.id!==p.id);if(role.id==='forger'){act(seatFor(p.id),'power');act(seatFor(p.id),'answer',{text:'First fake',second:'Second fake'});act(seatFor(r.t.subject),'answer',{text:'Real answer'});for(const q of r.players)if(!r.t.submissions[q.id])act(seatFor(q.id),'answer',{text:`Fake ${q.name}`});assert.equal(r.t.options.filter(o=>o.owners.includes(p.id)).length,2);assert.throws(()=>act(seatFor(p.id),'power'),/already used/);continue;}fillWriting(g);const truth=r.t.options.find(o=>o.truth),own=r.t.options.find(o=>o.owners.includes(p.id)),wrong=r.t.options.find(o=>!o.truth&&!o.owners.includes(p.id));
if(role.id==='reader')act(seatFor(other.id),'vote',{choices:[truth.id]});act(seatFor(p.id),'power',{target:other.id});assert.throws(()=>act(seatFor(p.id),'power',{target:other.id}),/already used/);
if(role.id==='detective'){const hint=game.snapshot(r,p.token).me.hint;assert.ok(hint.eliminated);assert.equal(r.t.options.find(o=>o.id===hint.eliminated).truth,false);assert.equal(game.snapshot(r,g.host.token).hint,undefined);}
if(role.id==='reader')assert.deepEqual(game.snapshot(r,p.token).me.hint.peek,[truth.id]);
act(seatFor(p.id),'vote',{choices:role.id==='lucky'?[truth.id,wrong.id]:[truth.id]});if(!r.t.votes[other.id])act(seatFor(other.id),'vote',{choices:['bounty','showboat'].includes(role.id)?[own.id]:[truth.id]});act(g.host,'advance');
const expected={detective:500,gambler:1000,accomplice:1000,bounty:1250,reader:500,showboat:1000,lucky:500}[role.id];assert.equal(p.score,expected,role.name);
}
});

test('Gambler loses 250 for a wrong guess',()=>{const g=setup(3);const p=g.game.eligible(g.room)[0];p.role=ROLES.find(r=>r.id==='gambler');fillWriting(g);g.act(g.seatFor(p.id),'power');const wrong=g.room.t.options.find(o=>!o.truth&&!o.owners.includes(p.id));g.act(g.seatFor(p.id),'vote',{choices:[wrong.id]});g.act(g.host,'advance');assert.equal(p.score,-250);});

test('Pause freezes countdown; missing truth skips without inventing an answer',()=>{const g=setup(4);const deadline=g.room.deadline;g.act(g.host,'pause');g.setNow(deadline+50000);g.game.tick();assert.equal(g.room.phase,'write');assert.throws(()=>g.act(g.seats[0],'answer',{text:'x'}),/paused/);g.act(g.host,'pause');assert.ok(g.room.deadline>deadline+50000);g.setNow(g.room.deadline+1);g.game.tick();assert.equal(g.room.phase,'reveal');assert.equal(g.room.t.skipped,true);assert.ok(g.room.players.every(p=>p.score===0));g.act(g.host,'next');assert.equal(g.room.turnIndex,1);});

test('Timeouts handle missing questions, missing drawings, and missing votes',()=>{const g=setup(4);for(let i=0;i<4;i++){g.act(g.host,'advance');g.act(g.host,'next');}assert.equal(g.room.phase,'questions');g.act(g.host,'advance');assert.equal(Object.keys(g.room.questions).length,4);for(let i=0;i<4;i++){g.act(g.host,'advance');g.act(g.host,'next');}assert.equal(g.room.phase,'truth');g.act(g.seatFor(g.room.t.subject),'truth',{text:'A sandwich'});g.act(g.host,'advance');assert.equal(g.room.t.skipped,true);g.act(g.host,'next');assert.equal(g.room.phase,'finished');});

test('Replacement question resets submissions and refunds powers used on that turn',()=>{const g=setup(4);const p=g.game.eligible(g.room)[0];p.role=ROLES.find(r=>r.id==='forger');g.act(g.seatFor(p.id),'power');const old=g.room.t;g.act(g.seatFor(old.subject),'skip');assert.notEqual(g.room.t.id,old.id);assert.notEqual(g.room.t.prompt,old.prompt);assert.equal(g.room.t.subject,old.subject);assert.equal(p.used,false);assert.deepEqual(g.room.t.submissions,{});});

test('Duplicate truth never turns into a bluff or awards its author lie points',()=>{const g=setup(3);const p=g.game.eligible(g.room)[0];g.act(g.seatFor(p.id),'answer',{text:'A movie theater'});g.act(g.seatFor(g.room.t.subject),'answer',{text:'A movie theater'});assert.equal(g.room.t.submissions[p.id],undefined);g.act(g.host,'advance');const truth=g.room.t.options.find(o=>o.truth);assert.deepEqual(truth.owners,[]);assert.equal(g.room.t.options.filter(o=>o.text==='A movie theater').length,1);});

test('Drawing validation rejects executable strings and out-of-bounds payloads',()=>{const g=setup(4);for(let i=0;i<4;i++){g.act(g.host,'advance');g.act(g.host,'next');}g.act(g.host,'advance');for(let i=0;i<4;i++){g.act(g.host,'advance');g.act(g.host,'next');}g.act(g.seatFor(g.room.t.subject),'truth',{text:'A dog'});const artist=g.seatFor(g.room.t.artist);assert.throws(()=>g.act(artist,'drawing',{strokes:[{color:'<script>',size:5,points:[[0,0]]}]}),/Invalid/);assert.throws(()=>g.act(artist,'drawing',{strokes:[{color:'#202031',size:5,points:[[2,0]]}]}),/coordinates/);});
