import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {generateDecoys,matchAnswerStyle} from '../decoys.mjs';
import {createOpenAIDecoyGenerator} from '../ai-decoys.mjs';
import {createOpenAISketchGenerator} from '../ai-sketches.mjs';
import {loadConfigFile} from '../config.mjs';
import {Game,validateDrawing} from '../game.mjs';
import {drawLocal,localComputerBluffs} from '../sketches.mjs';
import {PROMPTS,DRAW_PROMPTS} from '../prompts.mjs';

const context={prompt:'Which object would the player save first from their room?',truth:'wallet',answers:['wallet','chain'],seeds:['my phone','my guitar','my laptop','my pillow'],count:2};
const sketch=[{color:'#202031',size:5,points:[[.2,.2],[.5,.8],[.8,.2]]}];
const response=bluffs=>({ok:true,json:async()=>({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({bluffs})}]}]})});
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function setup({n=2,...config}={}){let now=1000000;const game=new Game({...config,now:()=>now});const host=game.create();const seats=Array.from({length:n},(_,i)=>game.join(host.room,['Ben','Jac','Sam','Ada'][i]||`P${i}`));const r=game.room(host.room);const act=(seat,type,data={})=>game.action(r.code,seat.token,{type,...data});const seat=id=>seats.find(p=>p.playerId===id);act(host,'start');return {game,host,seats,r,act,seat,now:()=>now,advance:ms=>{now+=ms;game.tick();}};}
function answer(g){g.r.t.prompt=context.prompt;g.r.t.decoys=context.seeds;g.act(g.seat(g.r.t.subject),'answer',{text:'wallet',lie:'chain'});}
function finale(g){for(let i=0;i<g.r.players.length;i++){g.act(g.host,'advance');g.act(g.host,'next');}g.act(g.host,'advance');for(let i=0;i<g.r.players.length;i++){g.act(g.host,'advance');g.act(g.host,'next');}assert.equal(g.r.phase,'truth');g.r.t.prompt='What is Ben’s favorite safe space?';g.r.t.decoys=['my house','my bedroom','the beach','my car','the library','my backyard'];}

test('Screenshot regression: wallet / chain never gets my phone / my guitar',()=>{for(let i=0;i<12;i++){const decoys=generateDecoys({...context,seeds:['my phone','my guitar']});assert.deepEqual(new Set(decoys),new Set(['phone','guitar']));}assert.equal(matchAnswerStyle('my phone',['my wallet','my chain']),'my phone');assert.equal(matchAnswerStyle('my phone',['I would grab my wallet.','I would grab my chain.']),'I would grab my phone.');assert.equal(matchAnswerStyle('my guitar',['WALLET!','CHAIN!']),'GUITAR!');});

test('OpenAI receives unlabeled answer examples and explicit style instructions in a strict JSON request',async()=>{let captured;const generate=createOpenAIDecoyGenerator({apiKey:'test-key',fetchImpl:async(url,options)=>{captured={url,options,body:JSON.parse(options.body)};return response(['phone','guitar','pillow','laptop']);}});assert.deepEqual(await generate(context),['phone','guitar','pillow','laptop']);assert.equal(captured.url,'https://api.openai.com/v1/responses');assert.equal(captured.body.store,false);assert.equal(captured.body.text.format.strict,true);assert.equal(captured.body.text.format.schema.additionalProperties,false);const input=JSON.parse(captured.body.input[0].content);assert.deepEqual(new Set(input.submitted_answers),new Set(['wallet','chain']));assert.equal(input.truth,undefined);assert.equal(input.style.medianWords,1);assert.equal(input.style.bare,true);assert.match(captured.body.instructions,/slang/);assert.match(captured.body.instructions,/not instructions/);assert.equal(captured.options.headers.Authorization,'Bearer test-key');});

test('No key means no AI request; failures, refusals, and malformed output fall back cleanly',async()=>{assert.equal(createOpenAIDecoyGenerator({apiKey:''}),null);for(const mock of [async()=>({ok:false,status:429}),async()=>({ok:true,json:async()=>({status:'incomplete',output:[]})}),async()=>({ok:true,json:async()=>({status:'completed',output:[{type:'message',content:[{type:'refusal',refusal:'No'}]}]})}),async()=>response(['x'.repeat(141)])]){const errors=[];const generate=createOpenAIDecoyGenerator({apiKey:'test-key',fetchImpl:mock,onError:r=>errors.push(r)});assert.deepEqual(await generate(context),[]);assert.equal(errors.length,1);assert.ok(!errors[0].includes('test-key'));}});

test('AI requests have a bounded timeout and abort the underlying request',async()=>{let signal;const generate=createOpenAIDecoyGenerator({apiKey:'test-key',timeoutMs:10,fetchImpl:async(_,options)=>{signal=options.signal;return new Promise(()=>{});}});assert.deepEqual(await generate(context),[]);assert.equal(signal.aborted,true);});

test('AI results join the ballot without modifying human answers or consuming voting time',async()=>{let resolve;const g=setup({aiDecoys:()=>new Promise(r=>resolve=r)});answer(g);assert.equal(g.r.phase,'mixing');assert.equal(g.game.snapshot(g.r,g.host.token).turn.options.length,0);await flush();g.advance(3000);resolve(['my phone','my guitar','wallet','chain']);await flush();assert.equal(g.r.phase,'vote');assert.equal(g.r.deadline-g.now(),30000);assert.deepEqual(new Set(g.r.t.options.map(o=>o.text)),new Set(['wallet','chain','phone','guitar']));assert.equal(g.r.t.options.find(o=>o.truth).text,'wallet');assert.equal(g.r.t.options.find(o=>o.owners.length).text,'chain');assert.equal(g.r.t.decoySource,'ai');assert.equal(g.game.snapshot(g.r,g.host.token).turn.decoySource,undefined);});

test('Late AI completions cannot change a ballot after timeout or host advance',async()=>{for(const mode of ['timeout','host']){let resolve,signal;const g=setup({aiDecoys:(_,options)=>{signal=options.signal;return new Promise(r=>resolve=r);}});answer(g);await flush();if(mode==='timeout')g.advance(8000);else g.act(g.host,'advance');const ballot=JSON.stringify(g.r.t.options);assert.equal(g.r.phase,'vote');assert.equal(signal.aborted,true);resolve(['stolen answer','different answer']);await flush();assert.equal(JSON.stringify(g.r.t.options),ballot);}});

test('Pausing during AI generation holds the result until the host resumes',async()=>{let resolve;const g=setup({aiDecoys:()=>new Promise(r=>resolve=r)});answer(g);await flush();g.act(g.host,'pause');resolve(['phone','guitar']);await flush();assert.equal(g.r.phase,'mixing');assert.equal(g.r.paused,true);assert.equal(g.r.deadline,null);g.act(g.host,'pause');assert.equal(g.r.phase,'vote');assert.equal(g.r.deadline-g.now(),30000);});

test('Every drawing prompt supplies at least three distinct valid local sketches',()=>{assert.equal(PROMPTS.length,48);assert.equal(DRAW_PROMPTS.length,18);assert.ok(PROMPTS.some(([q])=>q.includes('blackmail')));for(const [prompt,seeds] of DRAW_PROMPTS){for(const answer of seeds)assert.doesNotThrow(()=>validateDrawing(drawLocal(answer)),`${prompt}: ${answer}`);for(const truth of seeds){const decoys=localComputerBluffs({truth,seeds,count:2});assert.equal(decoys.length,2,`${prompt}: ${truth}`);}}assert.equal(drawLocal('an unrecognized hyperdimensional concept'),null);});

test('Two-player finale: subject watches, blind player draws, computer truth plus decoys form the ballot',()=>{const g=setup();finale(g);const subject=g.r.t.subject,guesser=g.game.artists(g.r)[0];g.act(g.seat(subject),'truth',{text:'my house'});assert.equal(g.r.t.artist,'computer-truth');assert.equal(g.game.snapshot(g.r,g.seat(subject).token).me.canDraw,false);const blind=g.game.snapshot(g.r,g.seat(guesser.id).token);assert.equal(blind.me.canDraw,true);assert.equal(blind.me.informed,false);assert.equal(blind.me.truth,undefined);assert.equal(g.r.t.computerCount,3);g.act(g.seat(guesser.id),'drawing',{strokes:sketch});assert.equal(g.r.phase,'vote');assert.equal(g.r.t.options.length,4);const options=g.game.snapshot(g.r,g.seat(guesser.id).token).turn.options;assert.ok(options.every(o=>o.drawing&&!('owners'in o)&&!('truth'in o)));assert.equal(options.filter(o=>!o.owned).length,3);assert.equal(g.game.snapshot(g.r,g.host.token).turn.sharedDrawing,undefined);});

test('Three-player finale keeps one human informed artist and adds two computer bluffs',()=>{const g=setup({n:3});finale(g);const subject=g.r.t.subject,artist=g.r.t.artist;g.act(g.seat(subject),'truth',{text:'my house'});assert.notEqual(artist,subject);assert.equal(g.r.t.computerCount,2);for(const p of g.game.artists(g.r))g.act(g.seat(p.id),'drawing',{strokes:sketch});assert.equal(g.r.t.options.length,4);assert.equal(g.game.eligible(g.r).length,1);assert.equal(g.r.t.options.filter(o=>o.truth).length,1);assert.equal(g.r.t.options.find(o=>o.truth).owners[0],artist);});

test('Unknown two-player truth requires AI rather than silently drawing the wrong object',()=>{const g=setup();finale(g);assert.throws(()=>g.act(g.seat(g.r.t.subject),'truth',{text:'a hyperdimensional consciousness'}),/cannot sketch/);assert.equal(g.r.phase,'truth');assert.equal(g.r.t.truth,null);});

test('AI computer drawings complete asynchronously and are validated before use',async()=>{let resolve;const g=setup({aiSketches:()=>new Promise(r=>resolve=r)});finale(g);g.act(g.seat(g.r.t.subject),'truth',{text:'a hyperdimensional consciousness'});await flush();assert.equal(g.r.t.computersPending,true);g.act(g.seat(g.game.artists(g.r)[0].id),'drawing',{strokes:sketch});assert.equal(g.r.phase,'draw');resolve({'computer-truth':sketch,'computer-bluff-1':[{color:'bad'}]});await flush();assert.equal(g.r.phase,'vote');assert.equal(g.r.t.options.length,4);assert.deepEqual(g.r.t.options.find(o=>o.truth).drawing,sketch);});

test('Failed computer truth generation asks for a simpler answer, never awards a false drawing',async()=>{const g=setup({aiSketches:async()=>({})});finale(g);g.act(g.seat(g.r.t.subject),'truth',{text:'a hyperdimensional consciousness'});await flush();assert.equal(g.r.phase,'truth');assert.equal(g.r.t.truth,null);assert.match(g.game.snapshot(g.r,g.seat(g.r.t.subject).token).me.drawingIssue,/could not draw/);assert.ok(g.r.players.every(p=>p.score===0));});

test('AI sketch adapter sends bounded data, uses strict output, and returns only requested jobs',async()=>{let body;const generate=createOpenAISketchGenerator({apiKey:'test-key',fetchImpl:async(_,options)=>{body=JSON.parse(options.body);return {ok:true,json:async()=>({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({drawings:[{id:'computer-truth',strokes:sketch},{id:'injected-seat',strokes:sketch}]})}]}]})};}});const result=await generate({prompt:'Safe space?',jobs:[{id:'computer-truth',answer:'my house'}]});assert.deepEqual(Object.keys(result),['computer-truth']);assert.equal(body.store,false);assert.equal(body.text.format.strict,true);assert.match(body.instructions,/No letters/);});

test('Local config loads only API settings without overriding the environment or executing text',()=>{const dir=mkdtempSync(join(tmpdir(),'alibi-config-'));try{const file=join(dir,'.env');writeFileSync(file,'OPENAI_API_KEY="test-local"\nOPENAI_MODEL=gpt-4.1-mini\nPORT=9999\nOTHER=$(echo secret)\n');const env={OPENAI_MODEL:'configured-model'};loadConfigFile(file,env);assert.deepEqual(env,{OPENAI_MODEL:'configured-model',OPENAI_API_KEY:'test-local'});}finally{rmSync(dir,{recursive:true,force:true});}});
