export const PROMPTS = [
 ['Which object in {name}’s room could blackmail them?', ['phone','laptop','mirror','pillow','laundry basket','trash can']],
 ['What would {name} get banned from a petting zoo for?', ['feeding the animals chips','trying to ride a goat','arguing with a llama','taking home a duck','climbing into a pen']],
 ['What would {name}’s FBI agent be most disappointed to learn?', ['how much I nap','my search history','how little I cook','my screen time','how often I order takeout']],
 ['What could {name} give a 40-minute TED Talk about with zero preparation?', ['parking','reality TV','sandwiches','group chat drama','video games','airport behavior']],
 ['What embarrassingly small inconvenience would be {name}’s villain origin story?', ['wet socks','a dead phone','a missing charger','a slow walker','a loud chewer']],
 ['Which food would {name} defend in court?', ['pineapple pizza','cereal for dinner','gas station sushi','cold fries','plain pasta']],
 ['What would {name} accidentally become the leader of?', ['a book club','a neighborhood watch','a conspiracy group','a dance class','a birdwatching club']],
 ['What is the most suspicious thing {name} could buy in bulk?', ['mayonnaise','rubber ducks','glitter','plastic forks','tiny hats']],
 ['What would {name} do first if everyone froze for ten minutes?', ['take a nap','read the group chat','get free snacks','move everyone’s shoes','leave the party']],
 ['What would be the worst possible slogan for {name}’s dating profile?', ['usually on time','my mom likes me','available after my nap','still figuring it out','great at ordering food']],
 ['What ordinary object does {name} have unreasonable beef with?', ['fitted sheets','automatic doors','printers','paper straws','coat hangers']],
 ['What would {name} spend their last five dollars on during an apocalypse?', ['an iced coffee','a lottery ticket','fries','a phone charger','gum']],
 ['What would {name} name a cult that is mostly about snacks?', ['the crunch bunch','midnight club','the pantry','snack council','the leftovers']],
 ['What would {name} be caught doing by a very judgmental ghost?', ['eating in bed','practicing an argument','talking to the mirror','sniffing laundry','watching the same movie again']],
 ['What would {name} try to expense on a business trip?', ['a massage','a karaoke room','a second dinner','matching pajamas','a psychic reading']],
 ['What is {name}’s most defensible red flag?', ['leaving messages unread','being late','having too many tabs open','canceling plans','eating other people’s fries']],
 ['What would {name} lie about to impress a pirate?', ['my swimming ability','my knife skills','how much I can drink','my sense of direction','owning a boat']],
 ['What would {name} bring to a sword fight instead of a sword?', ['a chair','a frying pan','an umbrella','a broom','pepper spray']],
 ['What would the documentary about {name}’s downfall be called?', ['it was on sale','just one more episode','I thought I muted myself','the group chat receipts','five more minutes']],
 ['What would {name} do to convince aliens they run Earth?', ['wear a crown','show them my calendar','point at a large building','put everyone on hold','make a spreadsheet']],
 ['What would {name} replace their hands with if they had to?', ['forks','claws','spatulas','magnets','tiny shovels']],
 ['What should {name} be legally required to apologize to?', ['my alarm clock','my houseplants','my car','my bank account','my laundry basket']],
 ['What would be {name}’s completely useless superpower?', ['finding missing socks','guessing microwave times','knowing who is typing','summoning one grape','falling asleep anywhere']],
 ['What animal would {name} trust to manage their money?', ['a raccoon','a crow','a dog','a goose','an owl']],
 ['What would {name} demand in a hostage negotiation with a goose?', ['my phone back','a sandwich','an apology','a ride home','a bathroom break']],
 ['What would {name} buy to fix a problem that therapy probably should handle?', ['new shoes','a gaming console','an expensive coffee machine','a plane ticket','a giant blanket']],
 ['What minor skill would {name} put on an aggressively misleading résumé?', ['parallel parking','making toast','remembering birthdays','assembling furniture','guessing the time']],
 ['What would {name} eat out of a mug to avoid washing a plate?', ['pasta','scrambled eggs','cereal','mashed potatoes','ice cream']],
 ['What would make {name} immediately abandon a treasure hunt?', ['rain','a spider','a dead phone','too many stairs','missing lunch']],
 ['What ridiculous rumor about {name} would their friends believe immediately?', ['I own a fog machine','I got lost in a parking lot','I cried at a commercial','I joined the wrong class','I bought a second air fryer']],
 ['What would {name} secretly be happy to find canceled?', ['a morning workout','a networking event','a camping trip','a group presentation','a family photo']],
 ['What would {name} put in a time capsule that would deeply confuse historians?', ['a parking ticket','a broken charger','a group chat screenshot','a single sock','a loyalty card']],
 ['What task would {name} trust a raccoon to do better than them?', ['organizing my room','choosing dinner','budgeting','finding my keys','folding laundry']],
 ['What would be the strangest place to find {name} taking a nap?', ['a dressing room','a movie theater','a wedding reception','a library floor','an airport gate']],
 ['What sentence would instantly summon {name} from another room?', ['there is free food','who wants coffee','we need your opinion','the game is starting','someone brought dessert']],
 ['What would {name} write a one-star review of even if it was free?', ['a party','a haircut','a sandwich','a guided tour','a yoga class']],
 ['What is {name}’s most embarrassing hill to die on?', ['fries are a meal','the book was worse','maps are confusing','cereal goes first','cold pizza is better']],
 ['What fake excuse has {name} actually used to leave a party?', ['an early meeting','a stomachache','feeding my dog','finishing homework','a family dinner']],
 ['What is something {name} believed for way too long?', ['teachers live at school','gum stays inside you for years','the moon follows the car','brown cows make chocolate milk','adults know what they are doing']],
 ['What is the weirdest thing {name} has actually eaten?', ['a whole lemon','a cricket','frozen fries','pet food by accident','an unidentifiable buffet item']],
 ['What would {name} name a goose that follows them everywhere?', ['Kevin','Goose Willis','tax fraud','mother','Greg']],
 ['What would {name} make everyone wear if they ran a tiny country?', ['slippers','tracksuits','matching hats','pajamas','capes']],
 ['What would {name} do if their microwave started giving life advice?', ['ask about my career','unplug it','argue with it','charge friends to use it','keep reheating my food']],
 ['What would {name} choose as the password to their evil lair?', ['password','letmein','my birthday','a pet’s name','the Wi-Fi password']],
 ['What is {name} most likely to mistake for a personality trait?', ['drinking coffee','being tired','liking spicy food','being early','owning a tote bag']],
 ['What would {name} steal from a hotel if there were no consequences?', ['the pillows','the robe','the breakfast machine','the tiny shampoo','the entire bed']],
 ['Which object would {name} save first from their room?', ['my phone','my hoodie','my laptop','my photo album','my guitar','my wallet']],
 ['What would {name} offer a dragon instead of fighting it?', ['leftover pizza','a playlist','a blanket','financial advice','a group hug']],
];

// Every seeded answer has a corresponding local sketch, so small groups can
// play without a model connection. Players can still type their own answers.
export const DRAW_PROMPTS = [
 ['What is {name}’s favorite safe space?', ['my house','my bedroom','the beach','my car','the library','my backyard']],
 ['Which animal would {name} hire as their life coach?', ['a goose','a cat','a dog','a bear','a spider','a fish']],
 ['Which object would {name} bring to a fight with a goose?', ['a fork','a sword','an umbrella','a shoe','a pillow','a toothbrush']],
 ['What food would {name} trust to make their life decisions?', ['a pizza','a potato','a banana','a burger','ice cream','a sandwich']],
 ['What object deserves a statue in {name}’s honor?', ['a phone','a pillow','a coffee mug','a toilet','a laptop','a chair']],
 ['What would {name} use as a crown if they became ruler of Earth?', ['a shoe','a banana','a traffic cone','a pizza','a book','an umbrella']],
 ['What would {name} bring on a first date with an alien?', ['a guitar','a pizza','a phone','a potato','a backpack','a cake']],
 ['Which object would {name} marry for the tax benefits?', ['a fridge','a laptop','a pillow','a car','a sofa','a coffee mug']],
 ['Where would {name} hide from one extremely persistent duck?', ['my house','a tent','a car','the library','a boat','the beach']],
 ['What would replace {name}’s head in a mildly upsetting dream?', ['a potato','a TV','a fish','a coffee mug','a crown','a ghost']],
 ['What would {name} choose as their emotional-support object?', ['a pillow','a phone','a guitar','a book','a coffee mug','a backpack']],
 ['What should appear on {name}’s personal warning sign?', ['a ghost','a spider','a banana','a toilet','a sword','a duck']],
 ['What would {name} throw at a zombie in a moment of panic?', ['a shoe','a phone','a fork','a book','a chair','a potato']],
 ['What object could most easily lure {name} into a suspicious van?', ['a pizza','a laptop','a coffee mug','a guitar','a pillow','a cake']],
 ['What would {name} send into space to represent humanity?', ['a duck','a sandwich','a toilet','a phone','a guitar','a book']],
 ['What would {name} worship if they accidentally started a religion?', ['a coffee mug','a pizza','a bed','a phone','a cat','a potato']],
 ['Which object in {name}’s room has seen too much?', ['a pillow','a laptop','a phone','a chair','a backpack','a wallet']],
 ['What would {name} bring to a job interview to establish dominance?', ['a sword','a crown','a duck','a chair','a guitar','a traffic cone']],
];
